### post an ad
PUT http://localhost:8080/ads/ddbef8db-feda-46fa-85cf-5fbf07b94602
Content-Type: application/json

{
  "title": "A title",
  "description": "A description",
  "price": 9.99
}

### get an ad by id
GET http://localhost:8080/ads/ddbef8db-feda-46fa-85cf-5fbf07b94602
Accept: application/json

### post a random ad
PUT http://localhost:8080/ads/{{$random.uuid}}
Content-Type: application/json

{
  "title": "A title",
  "description": "A description",
  "price": 9.99
}

### get a list of ads
GET http://localhost:8080/ads
Accept: application/json
